/* Healthy Kitchen — meal plan catalogue (from the live site) */
window.HK_PLANS = [
  { slug: "longevity", name: "Longevity Diet", price: 185, tags: ["Heart-healthy"],
    blurb: "Unlock a longer, healthier life. Boosts energy, supports heart health, and slows aging, keeping you active and vibrant.",
    long: "Inspired by the world's longest-living populations — plant-forward, antioxidant-rich, and balanced for cellular health. A lactose option is available on this plan." },
  { slug: "gut-healing", name: "Gut Healing Protocol", price: 180, tags: ["Gut support"],
    blurb: "Transform your health by healing your gut. Restores gut flora, improves digestion, and alleviates discomfort, leaving you revitalized.",
    long: "Our Gut Healing plan rebuilds a resilient microbiome with nutrient-dense, easy-to-digest meals. Expect less bloating, steadier energy, and better absorption — all dairy-, gluten- and sugar-free." },
  { slug: "autoimmune", name: "Autoimmune Protocol", price: 185, tags: ["Anti-inflammatory"],
    blurb: "Manage autoimmune conditions. Reduce inflammation, support immune function, and improve your quality of life.",
    long: "Built around the AIP framework: deeply anti-inflammatory, free from common triggers, and rich in the nutrients that calm an overactive immune response." },
  { slug: "low-fodmap", name: "Low FODMAP Protocol", price: 185, tags: ["Anti-bloat"],
    blurb: "Ease IBS and digestive discomfort. Cuts fermentable carbs that trigger bloating, gas, and cramping, restoring digestive calm.",
    long: "A structured low-FODMAP protocol built to calm a sensitive gut — meals free from the fermentable carbs that commonly trigger bloating, gas, and cramping, so digestion feels steady again." },
  { slug: "muscle-up", name: "Muscle UP", price: 200, tags: ["High-protein"],
    blurb: "High-protein, quality-carb meals that optimize muscle function, boost endurance, and accelerate recovery.",
    long: "Engineered for athletes: precise protein targets, clean complex carbs, and recovery-focused micronutrients — all in deliciously balanced, chef-made portions that optimize muscle function, boost endurance, and accelerate recovery." },
  { slug: "anticandida", name: "Anticandida Protocol", price: 185, tags: ["Low-sugar"],
    blurb: "Combat candida and restore balance. Reduces fungal infections, cuts sugar cravings, and boosts your immune system.",
    long: "A targeted low-sugar protocol that starves candida while nourishing you. Anti-fungal ingredients, zero added sugar, and balanced macros to bring your system back into equilibrium." },
  { slug: "easy-detox", name: "Easy Detox", price: 210, tags: ["Vegan"],
    blurb: "Refresh your body and mind. Flush out toxins, boost energy, and enhance health with our comprehensive program.",
    long: "A gentle, fully vegan reset. Whole-food, plant-based meals designed to support your body's natural detox pathways without leaving you hungry." },
  { slug: "detox-cleanse", name: "Detox & Cleanse", price: 330, tags: ["Vegan", "Juice"],
    blurb: "Revitalize with our Juice and Smoothie Detox. Nutrient-dense fruits and vegetables to detoxify, boost immunity, and glow.",
    long: "Freshly squeezed juices and nutrient-dense smoothies. The deepest reset we offer — for a clear head, a calm gut, and a healthy glow." },
];

window.HK_FEATURES = [
  { n: "01", title: "Clean Food & Quality", body: "We use only clean, quality ingredients and organic protein — the purest, nutrient-rich foods free from harmful pesticides and chemicals." },
  { n: "02", title: "Personalized Nutrition", body: "Customize your menu to your preferences and restrictions. Remove what you dislike or can't tolerate." },
  { n: "03", title: "Expertly Designed", body: "Menus designed by nutrition experts — balanced meals built around your specific health goals." },
  { n: "04", title: "Gourmet & Delicious", body: "Healthy food that tastes like a top-tier restaurant. Nutritious can also be delightful." },
  { n: "05", title: "Free From Gluten & Dairy", body: "Every dish is free from gluten, sugar, and harmful chemicals — clean, wholesome nutrition." },
  { n: "06", title: "Eco-Friendly Packaging", body: "Recyclable and biodegradable packaging, with mindful use of electricity and water in production." },
];

window.HK_REVIEWS = [
  { name: "Dr. Preya", role: "Doctor", text: "Nutritionally dense, varied, the highest quality, and incredibly tasty — truly clean food. As a doctor, I'd have no hesitation recommending Healthy Kitchen to my clients on their healing journeys." },
  { name: "Alexandra", role: "Member", text: "The meals are sophisticated and feel created with real thought and care. It uses less sugar than most, yet everything is still so tasty. Eat clean without sacrificing taste." },
  { name: "Frank", role: "Member", text: "Incredibly tasty food with clean ingredients delivered to my doorstep. My bloating is gone, I'm full of energy, and I can't wait for tomorrow's delivery. Dubai was waiting for this." },
];

window.HK_FAQ_ITEMS = [
  { q: "How does delivery work?", a: "Meals are chef-made fresh and delivered daily across Dubai, 7 AM–12 PM, in recyclable, eco-friendly packaging." },
  { q: "Can I customize my meals?", a: "Yes — every plan lets you remove up to 3 ingredients you dislike or can't tolerate, no extra charge." },
  { q: "What about allergies and intolerances?", a: "Every dish is dairy-, gluten- and sugar-free by default. Tell us about any other intolerances and we'll tailor your menu." },
  { q: "Can I pause or skip a day?", a: "Yes — pause or skip any day with 24 hours' notice, no penalties." },
  { q: "How is pricing calculated?", a: "Pricing depends on meals per day, calorie tier, and subscription length — longer plans unlock a bigger discount." },
  { q: "How clean is the food, really?", a: "Very. We source clean, nutrient-rich ingredients and organic protein, free from harmful pesticides and chemicals, for every plan." },
];

const HK_LOREM = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
];

window.HK_BLOG_POSTS = [
  {
    slug: "travel-proof-your-gut",
    category: "Gut Health",
    date: "13 Jul 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/07/travel-immunity-Dubai-e1783685342307-668x460.png",
    title: "Travel-Proof Your Gut: What to Eat Before, During and After Your Trip",
    excerpt: "New foods, long flights and broken routines unsettle digestion. A little planning on either side of the trip prevents most of it.",
    body: [
      "Travel is exciting; your digestive system is rarely as enthusiastic. Long flights, unfamiliar water and meals at odd hours all disturb the rhythm your gut relies on.",
      { h: "Before you fly" },
      "Spend the two or three days before departure eating simply — vegetables, whole grains, fermented foods. A well-fed microbiome copes far better with disruption than one already under strain.",
      { h: "On the road" },
      "Hydrate more than feels necessary, especially in the air. Keep one balanced meal a day that looks like your normal eating, and treat the rest as the holiday it is.",
      { h: "When you get home" },
      "Give yourself a week of gentle, fibre-rich meals rather than a punishing cleanse. Digestion resets quickly when it is fed properly, and our post-travel menus are built for exactly that week.",
    ],
  },
  {
    slug: "hydration-on-a-plate",
    category: "Wellness",
    date: "06 Jul 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/07/Summer-in-Dubai-e1783340431349-668x460.png",
    title: "Hydration on a Plate: Cooling, Water-Rich Meals for the Dubai Heat",
    excerpt: "In a Dubai summer your water bottle is only half the story — a large share of your fluid comes from food.",
    body: [
      "Most people think of hydration as something you drink. In practice, a meaningful share of your daily fluid arrives on your plate, and in a Dubai summer that share matters.",
      { h: "Foods that hold water" },
      "Cucumber, tomato, melon, courgette and leafy greens are mostly water by weight, and they carry minerals with them. So they hydrate better than water alone.",
      { h: "Why minerals come first" },
      "Fluid without electrolytes passes straight through you. Potassium and magnesium help your body hold on to what you drink, which is why we season and compose summer dishes with both in mind.",
      { h: "Light, cool, still satisfying" },
      "Chilled soups, big salads and fresh-fruit finishes keep you cool without leaving you hungry an hour later. That balance is the whole point of our summer menu.",
    ],
  },
  {
    slug: "eating-for-your-genes",
    category: "Nutrition",
    date: "29 Jun 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/06/DNA-Testing-e1782716339800-668x460.png",
    title: "Eating for Your Genes: What Nutrigenomics Actually Tells You",
    excerpt: "Dietary advice was written as if every body responds identically to food. Your genes say otherwise — within limits.",
    body: [
      "For decades, nutrition advice was issued as though every human body handled food the same way. Genetics has quietly dismantled that assumption.",
      { h: "Where genes really matter" },
      "Caffeine clearance, folate metabolism, lactose tolerance and how you handle saturated fat all vary genetically. Two people can follow identical diets and get measurably different results.",
      { h: "What a test cannot do" },
      "A gene panel is a tendency, not a verdict. Sleep, stress, movement and the microbiome still shape outcomes more than any single variant.",
      { h: "The practical version" },
      "Use testing to fine-tune, not to start. Build the boring foundation first — fibre, protein, plants, regular meals — then adjust the details around what your results suggest.",
    ],
  },
  {
    slug: "eating-to-train",
    category: "Nutrition",
    date: "22 Jun 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/06/Performance-Nutrition-for-Active-Men-in-Dubai-e1782115960524-668x460.png",
    title: "Eating to Train: Performance Nutrition for Active Men in Dubai",
    excerpt: "Most men in Dubai train harder than they recover. Training is scheduled; eating is improvised.",
    body: [
      "The gym session gets a slot in the calendar. Padel gets a slot. Recovery gets whatever is left, which is usually a late dinner and not much thought.",
      { h: "Protein, spread out" },
      "Total protein matters, but distribution matters too. Twenty-five to forty grams at each meal beats one enormous portion at night for building and repairing tissue.",
      { h: "Carbohydrates are not the enemy" },
      "If you train hard, you need fuel. Quality carbohydrates around training sessions restore glycogen and protect the muscle you are trying to build.",
      { h: "Absorption is the missing link" },
      "If digestion is inflamed, a high-protein diet is partly wasted. Settle the gut first and the same food starts to work harder — which is why our Muscle UP plan is built on clean, easily digested protein.",
    ],
  },
  {
    slug: "functional-foods-cellular-energy-nad",
    category: "Wellness",
    date: "15 Jun 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/06/NAD-e1781456280306-668x460.png",
    title: "Functional Foods That Support Cellular Energy and NAD+ Pathways",
    excerpt: "Every cell is a small energy factory. What you eat determines how well the machinery runs.",
    body: [
      "When your cells produce energy efficiently you feel it as stamina, clear thinking and quick recovery. When they do not, you call it tiredness.",
      { h: "What NAD+ does" },
      "NAD+ is a coenzyme central to turning food into usable energy. Levels tend to decline with age, and the pathways that recycle it depend on nutrients from the diet.",
      { h: "Foods that feed the pathway" },
      "B3-rich foods — fish, poultry, mushrooms, whole grains — supply the raw material. Polyphenol-rich vegetables, berries and green tea support the enzymes that use it.",
      { h: "The unglamorous multipliers" },
      "Sleep, movement and not overeating do more for cellular energy than any single ingredient. Food sets the conditions; habits do the rest.",
    ],
  },
  {
    slug: "mediterranean-heart-healthy-eating",
    category: "Nutrition",
    date: "08 Jun 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/06/Mediterranean-Diet-e1780904404140-668x460.png",
    title: "Mediterranean Eating: A Functional Approach to Cardiovascular Health",
    excerpt: "The most studied diet in the world is also one of the easiest to enjoy. Here is what actually does the work.",
    body: [
      "The Mediterranean pattern has more evidence behind it than any other way of eating. Its strength is not a single superfood but the shape of the whole plate.",
      { h: "Fats that help" },
      "Extra-virgin olive oil, nuts and oily fish supply monounsaturated and omega-3 fats. Both are associated with healthier blood lipids and lower inflammation.",
      { h: "Fibre and plants, in volume" },
      "Legumes, vegetables and whole grains feed the microbiome and help manage cholesterol. Variety matters more than quantity of any one item.",
      { h: "How to make it stick" },
      "Nobody sustains a diet they resent. The Mediterranean pattern lasts because it tastes good, which is why our Longevity plan borrows its structure.",
    ],
  },
  {
    slug: "foods-that-support-male-hormones",
    category: "Nutrition",
    date: "01 Jun 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/05/mans-health-month-e1780234375146-668x460.png",
    title: "Foods That Support Male Hormones: Eating for Testosterone and Vitality",
    excerpt: "Hormonal health in men is shaped less by supplements than by sleep, body composition and what is on the plate.",
    body: [
      "Testosterone gets discussed as though it were a supplement problem. In reality it responds to weight, sleep, stress and diet quality far more reliably.",
      { h: "Minerals that matter" },
      "Zinc and magnesium are both involved in hormone production, and both are commonly under-consumed. Seafood, seeds, nuts and legumes are the practical sources.",
      { h: "Enough fat, and the right kind" },
      "Hormones are built from cholesterol, so very low-fat diets can work against you. Olive oil, eggs, oily fish and avocado supply what the system needs.",
      { h: "What quietly suppresses it" },
      "Excess alcohol, chronic under-sleeping and rising visceral fat all push in the wrong direction. Fixing those three usually beats anything you can buy.",
    ],
  },
  {
    slug: "probiotic-foods-vs-supplements",
    category: "Gut Health",
    date: "25 May 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/05/digestive-health-day-e1779713827793-668x460.png",
    title: "Probiotic Foods vs Supplements: What Your Gut Really Needs",
    excerpt: "One of the most common questions we get. The honest answer: food first, supplements when there is a reason.",
    body: [
      "Probiotic capsules are easy to buy and easy to overestimate. They can help in specific situations, but they are not a substitute for how you eat.",
      { h: "What fermented food gives you" },
      "Yoghurt, kefir, kimchi and sauerkraut deliver live cultures alongside fibre, minerals and food matrix. That combination survives digestion better than a lone strain.",
      { h: "Prebiotics do the heavy lifting" },
      "Bacteria need feeding. Onion, garlic, oats, legumes and slightly under-ripe banana supply the fibres your existing microbes ferment.",
      { h: "When a supplement earns its place" },
      "After antibiotics, during travel, or with a specific diagnosis, a targeted strain can genuinely help. Otherwise, spend the money on vegetables.",
    ],
  },
  {
    slug: "5-day-anti-bloating-meal-plan",
    category: "Gut Health",
    date: "18 May 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/05/bloating-causes-Dubai-e1779019068715-668x460.png",
    title: "A 5-Day Anti-Bloating Plan: Eating for a Calmer Digestive System",
    excerpt: "Bloating is the complaint we hear most, and one of the most disruptive to an ordinary day.",
    body: [
      "Bloating rarely has one cause. Meal size, eating speed, fermentable carbohydrates and stress all contribute, often at the same time.",
      { h: "Days one and two: simplify" },
      "Cooked vegetables, lean protein and gentle grains. Warm food is easier to process than raw volume, and smaller portions eaten slowly help immediately.",
      { h: "Days three and four: identify" },
      "Reintroduce one suspect group at a time — dairy, wheat, legumes, certain fruits. Patterns become obvious quickly when everything else stays steady.",
      { h: "Day five: rebuild" },
      "Add fibre back gradually alongside fermented foods. If the pattern keeps returning, an intolerance test removes the guesswork.",
    ],
  },
  {
    slug: "7-serotonin-boosting-foods",
    category: "Wellness",
    date: "11 May 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/05/serotonin-dubai-e1778503590266-668x460.png",
    title: "7 Foods That Support Serotonin — and Your Mood",
    excerpt: "Most of the body's serotonin is made in the gut, which puts your plate closer to your mood than you might think.",
    body: [
      "The overwhelming majority of serotonin in the body is produced in the digestive tract. That single fact reframes how food relates to mood.",
      { h: "Start with tryptophan" },
      "Eggs, oily fish, turkey, tofu, oats, seeds and nuts all supply the amino acid serotonin is built from. Pair them with a little whole-grain carbohydrate to help it along.",
      { h: "Then feed the gut" },
      "A diverse, fibre-rich diet supports the bacteria involved in that production. Fermented foods help; ultra-processed food does the opposite.",
      { h: "Steady beats spiky" },
      "Blood-sugar crashes feel like mood crashes. Balanced meals at regular times do more for how you feel than any single ingredient.",
    ],
  },
  {
    slug: "brain-boosting-foods",
    category: "Wellness",
    date: "04 May 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/05/Mental-Health-Awareness-Month-e1777790800530-668x460.png",
    title: "Brain-Boosting Foods: Eating for Mood, Focus and Mental Clarity",
    excerpt: "Your brain is metabolically expensive. What you feed it shows up as focus — or fog.",
    body: [
      "The brain burns a disproportionate share of your daily energy and is unusually sensitive to what that energy arrives with.",
      { h: "Fats for structure" },
      "Omega-3 fats from oily fish, walnuts and flax are structural components of brain cell membranes. Low intake is associated with poorer mood and cognition.",
      { h: "Colour for protection" },
      "Berries, leafy greens and deeply coloured vegetables supply polyphenols that help manage oxidative stress. Variety across the week does more than any single serving.",
      { h: "Stability for focus" },
      "Sharp glucose swings blunt concentration. Protein, fibre and fat together keep the supply even, which is how our meals are composed by default.",
    ],
  },
  {
    slug: "foods-that-support-hormone-balance",
    category: "Nutrition",
    date: "27 Apr 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/04/hormone-imbalance-treatment-Dubai-e1777218455668-668x460.png",
    title: "Foods That Support Hormone Balance in Women",
    excerpt: "Hormonal health is not about avoiding a list of foods. It is about consistently supplying what the system needs.",
    body: [
      "Hormones are made, used and cleared using nutrients from your diet. That process runs on a surprisingly ordinary set of inputs.",
      { h: "Fibre clears what is finished" },
      "Oestrogen is metabolised and excreted through the gut. Adequate fibre keeps that route moving, which is why sluggish digestion and hormonal symptoms often travel together.",
      { h: "Protein and fat at every meal" },
      "Both stabilise blood sugar and supply hormone building blocks. Skipping either tends to show up as cravings and mood swings later in the day.",
      { h: "Cycle-aware eating" },
      "Needs shift across the month — more iron-rich food after menstruation, more magnesium in the second half. Small adjustments beat sweeping rules.",
    ],
  },
  {
    slug: "gut-healing-meal-plan-7-days",
    category: "Gut Health",
    date: "20 Apr 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/04/5A393339-3F21-450A-9591-212AF4061AC0-scaled-e1776688791332-668x460.jpg",
    title: "A Gut-Healing Week: 7 Days of Foods That Support Your Microbiome",
    excerpt: "Consistent patterns matter more than individual superfoods. A structured week beats a shopping list.",
    body: [
      "Research keeps pointing the same way: what you eat repeatedly matters more than any single ingredient you add.",
      { h: "Days one to three: calm" },
      "Cooked vegetables, bone broth or a good vegetable stock, gentle protein. The aim is to reduce irritation and let the gut lining settle.",
      { h: "Days four and five: diversify" },
      "Widen the range of plants. Thirty different plant foods across a week is a useful target, and it is easier than it sounds once herbs, seeds and spices count.",
      { h: "Days six and seven: consolidate" },
      "Add fermented foods and keep meals regular. That combination is the core of our Gut Healing Protocol, delivered so you do not have to plan it.",
    ],
  },
  {
    slug: "top-5-anti-inflammatory-meals",
    category: "Nutrition",
    date: "13 Apr 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/04/Top-Supplements-Dubai-e1776079384403-668x460.png",
    title: "Anti-Inflammatory Meals to Eat Alongside Your Supplement Routine",
    excerpt: "Supplements work best when the diet reinforces them — the most overlooked part of any protocol.",
    body: [
      "People invest carefully in supplements, then eat in a way that works against them. Diet is the base layer; supplements are the adjustment.",
      { h: "Oily fish and greens" },
      "Omega-3s plus leafy vegetables give you fats and micronutrients that inflammation-focused protocols usually target directly.",
      { h: "Turmeric with fat and pepper" },
      "Curcumin absorbs poorly on its own. Cooked into a dish with olive oil and black pepper, it does considerably better than a dry capsule.",
      { h: "Legumes and colour" },
      "Fibre feeds the bacteria that produce anti-inflammatory compounds in the gut. Deeply coloured vegetables supply the polyphenols alongside them.",
    ],
  },
  {
    slug: "best-gut-health-foods",
    category: "Gut Health",
    date: "06 Apr 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/04/Bone-Brothe-e1775412857489-668x460.png",
    title: "Best Gut Health Foods: What to Eat to Heal From the Inside Out",
    excerpt: "If you have been searching for gut-friendly food in Dubai, you are not alone. Here is where to start.",
    body: [
      "Gut repair is less exotic than the internet suggests. A handful of food groups, eaten consistently, does most of the work.",
      { h: "Broth and cooked vegetables" },
      "Easy to digest, mineral-rich, and gentle on an irritated lining. A sensible starting point when symptoms are active.",
      { h: "Fibre, in variety" },
      "Legumes, oats, seeds and a wide range of vegetables feed different bacterial populations. Diversity of plants matters more than volume of any one.",
      { h: "Fermented foods, in small amounts" },
      "Start with a spoonful, not a jar. Tolerance builds, and small regular servings are more useful than an occasional large one.",
    ],
  },
  {
    slug: "post-ramadan-reset",
    category: "Wellness",
    date: "30 Mar 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/03/17a96c90-1af8-4f9f-ab50-8ab1bfabcbf5-668x460.jpeg",
    title: "Post-Ramadan Reset: Restoring Energy and Calming Your Gut",
    excerpt: "A month of altered timing leaves its mark. Returning gently protects the progress you made.",
    body: [
      "After a month of different meal timing, the return to normal eating deserves as much thought as the fast itself.",
      { h: "Rebuild the rhythm" },
      "Three balanced meals at regular times re-anchor appetite and energy. Sudden large portions are the fastest route to discomfort.",
      { h: "Rehydrate properly" },
      "Water plus mineral-rich foods restores what long fasting hours depleted. Soups and water-rich vegetables help more than water alone.",
      { h: "Go easy on sugar" },
      "Celebration sweets are part of the season. Keeping them alongside protein and fibre rather than on an empty stomach smooths the energy curve.",
    ],
  },
  {
    slug: "eating-for-recovery",
    category: "Wellness",
    date: "23 Mar 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/03/Eating-for-Recovery-e1774251800575-668x460.png",
    title: "Eating for Recovery: Anti-Inflammatory Foods That Restore Balance",
    excerpt: "Recovery is not only about rest. It is a nutritional process with specific requirements.",
    body: [
      "Whether you are recovering from hard training, illness or a long stretch of stress, your body is rebuilding — and rebuilding needs materials.",
      { h: "Protein for repair" },
      "Adequate protein at each meal supplies the amino acids tissue repair depends on. Under-eating protein slows everything else down.",
      { h: "Colour for inflammation" },
      "Polyphenol-rich vegetables, berries, olive oil and oily fish all help modulate the inflammatory response rather than simply suppress it.",
      { h: "Sleep is a nutrient" },
      "No diet compensates for chronic short sleep. Lighter, earlier dinners are one of the simplest ways to improve both.",
    ],
  },
  {
    slug: "after-ramadan-normal-eating",
    category: "Gut Health",
    date: "16 Mar 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/03/Eid-Dubai-e1773674307522-668x460.png",
    title: "After Ramadan: Returning to Normal Eating Without Digestive Stress",
    excerpt: "Eid Mubarak. The tables are full and the temptation to eat everything at once is very real.",
    body: [
      "After a month of fasting, digestion has adapted to a particular schedule. Overwhelming it on day one is a common and avoidable mistake.",
      { h: "Smaller, more often" },
      "Start with moderate portions across the day rather than two large sittings. Your digestive capacity returns within a few days.",
      { h: "Protein and vegetables first" },
      "Anchoring each meal in protein and vegetables leaves less room for the sugar spike, without banning anything.",
      { h: "Keep what worked" },
      "Many people eat more mindfully during Ramadan. That habit is worth keeping long after the month ends.",
    ],
  },
  {
    slug: "protein-fibre-healthy-fats",
    category: "Nutrition",
    date: "09 Mar 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/03/macronutriets-dubai-e1773048824835-668x460.png",
    title: "Protein, Fibre and Healthy Fats: The Trio That Keeps You Full",
    excerpt: "Ever finished a meal and felt hungry an hour later? The composition of the plate is usually why.",
    body: [
      "Hunger an hour after eating is rarely about willpower. It is about what the meal was made of.",
      { h: "Protein sets satiety" },
      "Protein is the most satiating macronutrient, and it protects muscle while you are at it. Every meal should have a clear source.",
      { h: "Fibre slows the curve" },
      "Vegetables, legumes and whole grains slow digestion and feed the microbiome. They flatten the spike that leads to the crash.",
      { h: "Fat carries flavour and fullness" },
      "Olive oil, nuts, seeds and avocado extend satiety and make food worth eating. Together the three turn a meal into several hours of steady energy.",
    ],
  },
  {
    slug: "mid-ramadan-fatigue-bloating",
    category: "Gut Health",
    date: "02 Mar 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/03/Ramadan-Fasting-e1772444259759-668x460.png",
    title: "Mid-Ramadan Fatigue and Bloating: Adjusting Meals for Better Energy",
    excerpt: "What felt manageable in the first days often shifts by the middle of the month.",
    body: [
      "By mid-Ramadan, many people notice fatigue and bloating creeping in. Usually the fix is in how the two meals are built, not in the fasting itself.",
      { h: "Rethink iftar" },
      "Breaking the fast with dates and water, then pausing before the main meal, prevents the rush that causes discomfort. Eat slowly; the body needs the ramp.",
      { h: "Make suhoor count" },
      "Protein, fibre and fat at suhoor carry you much further than refined carbohydrates. Oats, eggs, yoghurt and nuts are the reliable options.",
      { h: "Hydrate between, not during" },
      "Spread fluids across the evening rather than in two large volumes. Mineral-rich foods help you retain what you drink.",
    ],
  },
  {
    slug: "how-to-eat-during-ramadan",
    category: "Nutrition",
    date: "23 Feb 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/02/Ramadan-Dubai-e1771840673827-668x460.png",
    title: "How to Eat During Ramadan Without Energy Crashes or Overeating",
    excerpt: "Meal timing changes, sleep shifts, and long fasting hours test the best intentions.",
    body: [
      "Ramadan reorganises the day. With a little structure, the two meals available can support energy rather than swing it.",
      { h: "Build iftar in stages" },
      "Hydration and something light first, then a balanced main meal twenty minutes later. This alone prevents most of the heaviness people describe.",
      { h: "Protect suhoor" },
      "Skipping it almost guarantees a difficult afternoon. Slow carbohydrates with protein and fat is the combination that lasts.",
      { h: "Moderate the sweets" },
      "There is no need to eliminate them. Eaten after a balanced meal rather than instead of one, they cost far less in energy.",
    ],
  },
  {
    slug: "why-consistency-beats-dieting",
    category: "Lifestyle",
    date: "16 Feb 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/02/healthy-meal-plan-e1771248274768-668x460.png",
    title: "Why Consistency Beats Dieting",
    excerpt: "Quick fixes get the attention. The people who actually change their health do something far less interesting.",
    body: [
      "Short-term diets produce short-term results almost by definition. What holds up over years is structure.",
      { h: "The problem with intensity" },
      "Highly restrictive plans work until life interrupts them. Because they depend on perfect conditions, they rarely survive a busy month.",
      { h: "What structure looks like" },
      "Regular meals, adequate protein, plenty of plants, and food you actually want to eat. Unremarkable on any given day; decisive over a year.",
      { h: "Removing the friction" },
      "Most people fail on logistics, not knowledge. Having good food already prepared is the single most effective intervention we know of.",
    ],
  },
  {
    slug: "food-mood-emotional-eating",
    category: "Wellness",
    date: "09 Feb 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/02/HK-Valentine-e1770646365953-668x460.png",
    title: "Food, Mood and Emotional Eating",
    excerpt: "Emotional eating is usually framed as weak willpower. It is far more physiological than that.",
    body: [
      "Reaching for food under stress is not a character flaw. Blood sugar, sleep debt and stress hormones all push in that direction.",
      { h: "Undereating drives overeating" },
      "Long gaps between meals leave you biologically primed to overeat later. Regular meals remove most of the pressure before it builds.",
      { h: "Stress changes what appeals" },
      "Cortisol shifts appetite toward sugar and fat. Knowing that makes it easier to plan around rather than argue with.",
      { h: "Build the floor first" },
      "Protein at breakfast, meals at predictable times, enough sleep. Most people find the emotional pull shrinks considerably once those are in place.",
    ],
  },
  {
    slug: "eating-for-stable-energy",
    category: "Nutrition",
    date: "02 Feb 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/02/wearables-e1770026383438-668x460.png",
    title: "Eating for Stable Energy: Why Skipping Meals Backfires",
    excerpt: "Low energy gets blamed on sleep and stress. Often the cause is simpler and closer to lunch.",
    body: [
      "Skipping meals feels efficient and disciplined. Metabolically it is neither — it tends to produce fatigue, cravings and a larger evening appetite.",
      { h: "The crash cycle" },
      "A long gap drops blood sugar; the body compensates with stress hormones; you end up wired, then flat. Repeating this daily is exhausting.",
      { h: "Three meals, properly built" },
      "Each with protein, fibre and fat. Most people need nothing more elaborate than that to feel dramatically steadier within a week.",
      { h: "Snacks with a purpose" },
      "If gaps are long, a small protein-and-plant snack bridges them. Fruit with nuts beats a bar every time.",
    ],
  },
  {
    slug: "longevity-nutrition-daily-choices",
    category: "Wellness",
    date: "26 Jan 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/01/Longevity-Isnt-Anti-Aging-Its-About-Staying-Strong-Sharp-Mobile-e1769423701232-668x460.png",
    title: "Longevity Nutrition: How Daily Food Choices Affect How You Age",
    excerpt: "Longevity is imagined as clinics and supplements. In practice it is built out of ordinary meals.",
    body: [
      "The evidence on healthy ageing keeps returning to daily habits rather than interventions. Diet is the one you repeat three times a day.",
      { h: "Plants, in quantity and variety" },
      "The long-lived populations studied most closely all eat mostly plants, with legumes and whole grains at the centre. Fibre and polyphenols are the common thread.",
      { h: "Protein for the decades ahead" },
      "Maintaining muscle protects independence later. Adequate protein plus resistance training is the most reliable pairing we have.",
      { h: "Less of the obvious things" },
      "Ultra-processed food, added sugar and excess alcohol shorten the healthy years more than most people expect. Reducing them is unglamorous and effective.",
    ],
  },
  {
    slug: "why-regular-meals-beat-fasting",
    category: "Nutrition",
    date: "19 Jan 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/01/eating-regular-meal-e1768807961879-668x460.png",
    title: "Why Regular Meals Matter More Than Fasting for Most People",
    excerpt: "Fasting has real uses. For most people, eating regularly is the higher-yield change.",
    body: [
      "Intermittent fasting became popular because it is simple to describe. That is not the same as being the best option for you.",
      { h: "Who fasting suits" },
      "Some people genuinely do well on a compressed eating window, particularly if it curbs late-night grazing. It is one tool among several.",
      { h: "Who it works against" },
      "Anyone under-eating protein, managing hormonal symptoms, training heavily or prone to binge patterns often does worse. Skipping meals is not neutral.",
      { h: "The better default" },
      "Regular balanced meals stabilise energy, protect muscle and reduce cravings. Master that before experimenting with timing.",
    ],
  },
  {
    slug: "blood-sugar-balance-foundation",
    category: "Nutrition",
    date: "12 Jan 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/01/blood-sugar-e1768212348841-668x460.png",
    title: "Blood Sugar Balance: The Foundation of Energy, Weight and Mood",
    excerpt: "If one thing explains afternoon crashes, cravings and mood dips, it is usually this.",
    body: [
      "Blood sugar stability is the least glamorous topic in nutrition and the one that changes how people feel fastest.",
      { h: "What causes the spike" },
      "Refined carbohydrates eaten alone. The same food alongside protein, fat and fibre produces a much gentler curve.",
      { h: "Order matters" },
      "Vegetables and protein before the starch on your plate measurably reduces the glucose response. It costs nothing to try.",
      { h: "Movement after meals" },
      "A ten-minute walk after eating helps muscles clear glucose. Small, repeatable, surprisingly effective.",
    ],
  },
  {
    slug: "the-january-reset",
    category: "Wellness",
    date: "05 Jan 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/01/metabolic-health-e1767606274300-668x460.png",
    title: "The January Reset: What Actually Helps Your Body Recover",
    excerpt: "January arrives with motivation and exhaustion in equal measure. Only one of them is useful.",
    body: [
      "After weeks of disrupted routine, heavier meals and late nights, the instinct is to overcorrect. That rarely lasts past the second week.",
      { h: "Restore, do not punish" },
      "Regular meals, more vegetables, more water and earlier nights. Nothing dramatic, and far more effective than a detox tea.",
      { h: "Digestion first" },
      "A stretch of gentle, fibre-rich food settles the system quickly. Most of the heaviness people describe resolves within a week.",
      { h: "Pick habits, not rules" },
      "One protein-rich breakfast, one daily walk, one week of prepared dinners. Habits that survive February are the ones worth choosing.",
    ],
  },
  {
    slug: "why-extreme-detoxes-backfire",
    category: "Wellness",
    date: "29 Dec 2025",
    image: "https://healthykitchen.delivery/wp-content/uploads/2025/12/detox-gone-wrong-e1767001902839-668x460.png",
    title: "Why Extreme Detoxes Backfire After the Holidays",
    excerpt: "Detox teas and week-long juice fasts promise a fast reset. The body has other plans.",
    body: [
      "Your liver and kidneys detoxify continuously and competently. What they need is nutrients, hydration and sleep — not deprivation.",
      { h: "What restriction actually does" },
      "Very low intake slows metabolism, drops energy and often ends in rebound eating. The scale moves; nothing improves.",
      { h: "What supports the process" },
      "Cruciferous vegetables, leafy greens, adequate protein and plenty of water give the liver the raw material it uses. Fibre carries the end products out.",
      { h: "A cleanse worth doing" },
      "Short, nutrient-dense and food-based — which is how our Easy Detox and Detox & Cleanse plans are designed.",
    ],
  },
  {
    slug: "hidden-impact-sugar-alcohol-late-meals",
    category: "Wellness",
    date: "22 Dec 2025",
    image: "https://healthykitchen.delivery/wp-content/uploads/2025/12/christmas-food-e1766396849802-668x460.png",
    title: "The Hidden Impact of Sugar, Alcohol and Late Meals on Inflammation",
    excerpt: "Many people feel heavier and more tired in December before the holidays even begin.",
    body: [
      "Three ordinary December habits compound quietly: more sugar, more alcohol and later dinners. Each affects inflammation and sleep.",
      { h: "Sugar and the spike" },
      "Repeated glucose spikes drive inflammatory signalling and disturb energy. Pairing sweets with protein and fibre softens both.",
      { h: "Alcohol and recovery" },
      "Even moderate drinking fragments sleep and irritates the gut lining. Alcohol-free days do more than most supplements.",
      { h: "Timing counts" },
      "Late heavy meals mean digesting when you should be sleeping. Eating earlier is the cheapest anti-inflammatory intervention available.",
    ],
  },
  {
    slug: "eat-well-during-the-holidays",
    category: "Lifestyle",
    date: "15 Dec 2025",
    image: "https://healthykitchen.delivery/wp-content/uploads/2025/12/healthy-eating-e1765791293956-668x460.png",
    title: "How to Eat Well During the Holidays Without Starting Over in January",
    excerpt: "Indulgence in December, guilt in early January, strict reset after. The cycle is optional.",
    body: [
      "The holiday-then-penance cycle is exhausting and unnecessary. A middle path keeps both the celebrations and your baseline intact.",
      { h: "Do not arrive hungry" },
      "Skipping meals before an event guarantees overeating at it. A protein-rich breakfast changes the whole evening.",
      { h: "Choose deliberately" },
      "Have the things you actually love and skip the ones you are eating out of proximity. Most of a buffet is not worth it.",
      { h: "Return, do not restart" },
      "One indulgent meal changes nothing. Going back to normal at the next meal is the entire skill.",
    ],
  },
  {
    slug: "food-as-biohacking",
    category: "Wellness",
    date: "08 Dec 2025",
    image: "https://healthykitchen.delivery/wp-content/uploads/2025/12/Biohacking-Longevity-e1765188159373-668x460.png",
    title: "Food as Biohacking: Everyday Nutrition That Upgrades Energy and Performance",
    excerpt: "Biohacking suggests wearables and infusions. The highest-leverage tool is on your plate three times a day.",
    body: [
      "Devices and supplements can be useful, but they are adjustments to a baseline. Food is the baseline.",
      { h: "Protein and fibre as defaults" },
      "Hit both at every meal and most of the metrics people chase — energy, satiety, glucose stability — improve without further intervention.",
      { h: "Timing as a lever" },
      "Bigger earlier meals, lighter earlier dinners. Aligning intake with daylight improves sleep and glucose control for most people.",
      { h: "Measure what you change" },
      "If you track anything, track how you feel at 3pm and how you sleep. Both respond quickly to what you eat.",
    ],
  },
  {
    slug: "eating-for-longevity-habits",
    category: "Wellness",
    date: "03 Dec 2025",
    image: "https://healthykitchen.delivery/wp-content/uploads/2025/12/Longevity--e1764603029455-668x460.png",
    title: "Eating for Longevity: Habits That Help You Live Better, Longer",
    excerpt: "Longevity is no longer about adding years to life, but life to years.",
    body: [
      "The research consistently favours patterns over interventions. A handful of habits, repeated for decades, does the work.",
      { h: "Mostly plants, plenty of fibre" },
      "Legumes, whole grains, vegetables, nuts and olive oil form the backbone of every long-lived dietary pattern studied.",
      { h: "Enough protein, and enough muscle" },
      "Muscle mass predicts independence in later life. Protein at every meal plus regular resistance work is the pairing that protects it.",
      { h: "Consistency over perfection" },
      "Nobody eats flawlessly. The direction of travel across years matters more than any single week.",
    ],
  },
  {
    slug: "food-and-hormones-cycles-mood-energy",
    category: "Nutrition",
    date: "24 Nov 2025",
    image: "https://healthykitchen.delivery/wp-content/uploads/2025/11/womens-health-668x460.png",
    title: "Food and Hormones: Meals That Support Better Cycles, Mood and Energy",
    excerpt: "Women's hormones shape mood, appetite, metabolism, sleep and stress resilience — and respond to food.",
    body: [
      "Hormonal symptoms are often treated as something to endure. Diet will not fix everything, but it changes the baseline more than most people realise.",
      { h: "Blood sugar first" },
      "Glucose swings amplify mood and energy symptoms. Balanced meals at regular times are the highest-yield starting point.",
      { h: "Fibre for clearance" },
      "Hormone metabolites leave via the gut. Adequate fibre and regular digestion keep that pathway working.",
      { h: "Micronutrients that matter" },
      "Iron, magnesium, B vitamins and omega-3s all play defined roles. Food sources beat guessing with capsules.",
    ],
  },
  {
    slug: "blood-sugar-balance-made-simple",
    category: "Nutrition",
    date: "17 Nov 2025",
    image: "https://healthykitchen.delivery/wp-content/uploads/2025/11/blood-sugar-post-e1763388782180-668x460.png",
    title: "Blood Sugar Balance Made Simple",
    excerpt: "Rushed meals, busy schedules and constant stress — few people realise how much of their mood tracks glucose.",
    body: [
      "You do not need a monitor to benefit from steadier blood sugar. A few structural habits deliver most of the effect.",
      { h: "Never eat carbohydrate alone" },
      "Add protein, fat or fibre to anything starchy or sweet. The same food, a much gentler response.",
      { h: "Front-load the day" },
      "A savoury, protein-rich breakfast sets the tone for hours. Sweet breakfasts tend to produce a hungry, unfocused morning.",
      { h: "Move a little, often" },
      "Short walks after meals help clear glucose. Combined with balanced plates, most people notice the difference within days.",
    ],
  },
  {
    slug: "energy-on-a-plate-5-meals-that-fight-the-august-slump",
    category: "Nutrition",
    date: "17 Aug 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/08/fatigue-dubai-e1786964133694.png",
    title: "Energy on a Plate: 5 Meals That Fight the August Slump",
    excerpt: "Do you feel flat by mid-afternoon this August? You are not alone — the right meals can help you climb back out.",
    body: [
      "Do you feel flat by mid-afternoon this August? You are not alone. The post-holiday slump leaves many people quietly drained. Fortunately, the right energy-boosting meals in Dubai can help you climb back out.",
      "Food steadies your energy far more than most people realise. The right meals keep you level all day, without the caffeine rollercoaster. At Healthy Kitchen, we design our energy-boosting meals in Dubai to do exactly that.",
      { h: "Why energy dips after a holiday" },
      "Holidays shift your routine and your meals. Extra sugar and irregular timing throw your energy off balance. As a result, tiredness lingers once normal life resumes.",
      "Balanced meals reset that rhythm. They release energy slowly and steadily. Therefore, they help smooth out the peaks and crashes that leave you reaching for a snack.",
      { h: "1. A protein-rich breakfast" },
      "Energy starts with the very first meal. Protein at breakfast keeps you full and focused for longer. So we build our morning dishes around eggs, legumes and wholegrains.",
      { h: "2. A leafy, mineral-rich lunch" },
      "Leafy greens supply magnesium and iron, and both support steady energy. Consequently, our lunches feature plenty of colourful, mineral-rich vegetables alongside good protein.",
      { h: "3. A balanced grain bowl" },
      "Whole grains give slow-release fuel that lasts. Paired with protein and vegetables, they keep you level through the afternoon. This simple balance beats the classic 3pm dip.",
      { h: "4. An iron-friendly main" },
      "Low iron often drains energy quietly. Our iron-friendly mains combine lean protein with vitamin-C-rich vegetables. Together, they help your body absorb more of the iron on the plate.",
      { h: "5. A light, restful dinner" },
      "Heavy dinners disturb sleep, which then drains tomorrow's energy. Lighter evening meals digest more easily. As a result, you rest better and wake sharper.",
      { h: "Hydration: the overlooked energiser" },
      "Tiredness is sometimes just thirst in disguise. Even mild dehydration can leave you foggy and flat. In a Dubai summer, that risk rises for everyone.",
      "So water belongs in any list of energy-boosting meals. Water-rich foods help, too, from cucumber to melon. Because hydration is so easy to forget, we build it into the way we plan your day.",
      { h: "Timing matters as much as content" },
      "What you eat drives energy, but so does when you eat it. Long gaps between meals invite the mid-afternoon crash. Regular, balanced meals keep your energy on an even keel.",
      "This is where planning quietly pays off. With meals ready at the right times, you stop running on empty. As a result, steady energy becomes the norm rather than the exception.",
      { h: "Caffeine, sugar and the crash cycle" },
      "It is tempting to fight tiredness with coffee and a snack. The lift is real, but it is brief. Soon after, the crash pulls you lower than before.",
      "Balanced meals break that cycle gently. They provide steady fuel without the spike. Therefore, you rely less on quick fixes and feel more like yourself throughout the day.",
      { h: "Snacks that support, not sabotage" },
      "The right snack keeps energy steady between meals. Pair a little protein with fruit or vegetables. So a handful of nuts with an apple beats a sugary bar every time.",
      { h: "Let us fuel your comeback" },
      "Beating the slump should be simple, not another chore. With the right meals ready to go, it becomes automatic. Explore our energy-boosting meals and fight the August slump, delivered fresh to your door.",
    ],
  },
  {
    slug: "the-post-travel-reset-menu-7-days-of-gut-friendly-eating",
    category: "Gut Health",
    date: "10 Aug 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/08/post-travel-gut-reset-dubai-e1786193012715.png",
    title: "The Post-Travel Reset Menu: 7 Days of Gut-Friendly Eating",
    excerpt: "You are rested, yet your gut may feel oddly off. A week of gentle, gut-friendly meals is the answer.",
    body: [
      "Coming home from holiday feels good and strange at once. You are rested, yet your gut may feel oddly off. Rich food and travel often leave you heavy and slow. A week of gut-friendly reset meals is the perfect, gentle answer.",
      "You do not need an extreme cleanse to feel like yourself again. Instead, a steady run of balanced, gut-friendly reset meals does the work quietly, one day at a time.",
      { h: "Why gentle beats harsh" },
      "Crash cleanses promise fast results. In truth, they often leave you drained and irritable. Skipping meals can also stress the gut further, which is the opposite of what you want.",
      "A reset takes a kinder path. It feeds your body with whole, balanced food. As a result, digestion recovers on its own terms, and the changes are far easier to sustain.",
      { h: "Days one and two: lighten the load" },
      "Start gently to ease your system back. Focus on vegetables, soups and plenty of water. These foods are light and simple to digest after a heavy few weeks.",
      "Our chilled soups and fresh salads suit these days well. They settle the stomach without weighing you down. So you feel lighter almost at once.",
      { h: "Days three to five: feed your microbes" },
      "Now bring in more fibre and variety. Include legumes, whole grains and colourful vegetables. Because fibre feeds your good bacteria, this stage rebuilds balance where it matters.",
      "Add fermented foods where you can, too. Yoghurt and other cultured options support the gut nicely. Our balanced mains make this step effortless.",
      { h: "Days six and seven: steady the ship" },
      "End the week with simple, repeatable meals. Pair protein with vegetables at each sitting. Meanwhile, keep hydration high and your sleep regular.",
      "By day seven, most people feel noticeably brighter. Digestion settles and energy returns. A happier gut tends to lift the whole body with it.",
      { h: "What makes a meal gut-friendly" },
      "Not every healthy-looking meal is easy on the gut. The best gut-friendly reset meals are rich in fibre and gentle on digestion. They lean on vegetables, whole grains, legumes and lean protein.",
      "Just as importantly, they avoid the heavy, ultra-rich dishes that slow you down. We balance every plate with this in mind. So each meal supports recovery rather than working against it.",
      { h: "Hydration is part of the plan" },
      "Food is only half of a good reset. Hydration matters just as much, especially after flights and a Dubai summer. Water supports digestion and helps everything move as it should.",
      { h: "Keep it going beyond seven days" },
      "A seven-day reset is a strong start, not a finish line. The habits you build can quietly continue afterward. Fibre-rich meals and steady routines keep the benefits alive.",
      "That is where a regular delivery helps most. With good food arriving anyway, healthy choices become the default. As a result, your gut stays supported long after the reset week ends.",
      { h: "Let us plan your reset week" },
      "A full week of healthy meals can sound like effort. With Healthy Kitchen, it is genuinely effortless, because we plan, cook and deliver each dish. Ready to feel like yourself again?",
    ],
  },
  {
    slug: "foods-that-calm-eating-for-a-regulated-nervous-system",
    category: "Nutrition",
    date: "03 Aug 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/08/Nervous-System-Dubai-e1785687102534.png",
    title: "Foods That Calm: Eating for a Regulated Nervous System",
    excerpt: "When you feel wound-up, food can quietly help you settle — and the most effective foods are everyday ones.",
    body: [
      "When you feel wound-up, food can quietly help you settle. In fact, some of the most effective foods that calm the nervous system are simple, everyday ingredients. What you eat shapes how calm or alert you feel, meal after meal.",
      "At Healthy Kitchen, we build dishes with this in mind. Our calming meals focus on the nutrients that support rest and recovery. As a result, they help your body ease out of a busy day rather than stay stuck in it.",
      { h: "The gut-brain connection" },
      "Your gut and brain talk constantly through a two-way link. A large share of your calm-signalling chemistry actually begins in the gut. Therefore, what you feed your gut affects how settled you feel.",
      "A balanced, fibre-rich diet supports this connection. So does a steady supply of whole foods rather than ultra-processed ones. Because of that, our menu leans on vegetables, legumes and gentle whole grains.",
      { h: "Magnesium: the calm mineral" },
      "Magnesium helps muscles and nerves relax. When levels run low, you may feel tense, restless or slow to sleep. Consequently, it is one of the most important minerals among foods that calm the nervous system.",
      "Leafy greens, seeds, nuts and legumes are naturally rich in magnesium. We include these across our menu on purpose. So every serving quietly supports a steadier, calmer state.",
      { h: "Foods that steady your energy" },
      "Sharp blood-sugar swings can leave you jittery and on edge. Balanced meals prevent those spikes and crashes. As a result, your mood and energy stay far more even through the afternoon.",
      "We pair protein, fibre and healthy fats in each dish for exactly this reason. This combination releases energy slowly. So you feel steady rather than frazzled, without relying on caffeine or sugar to cope.",
      { h: "Tryptophan and your evening wind-down" },
      "Some calming foods work best later in the day. Foods rich in tryptophan, an amino acid, help your body wind down toward sleep. Turkey, eggs, seeds and oats all supply it.",
      "Pairing these with a little whole-grain carbohydrate can help, too. The combination supports the body's natural evening rhythm. As a result, a well-planned dinner may leave you calmer and readier for rest.",
      { h: "What to ease off when you feel wired" },
      "Some foods quietly work against a calm system. Too much caffeine, sugar and alcohol can all keep you on edge. So easing off them often helps as much as adding calming foods.",
      "You do not need to cut anything out completely. A gentler balance is usually enough. Because small changes add up, even modest swaps can leave you noticeably steadier.",
      { h: "Let your meals do the work" },
      "Eating for calm should be simple and genuinely enjoyable. With the right meals ready to go, it becomes effortless. Let us handle the shopping, cooking and portioning, and bring a little more calm to your table.",
    ],
  },
  {
    slug: "the-7-day-post-travel-reset-menu-functional-meals",
    category: "Nutrition",
    date: "27 Jul 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/07/Functional-Nutrition-Plan-Dubai-e1784978739194.png",
    title: "The 7-Day Post-Travel Reset Menu: Functional Meals to Rebalance After Holiday Eating",
    excerpt: "You feel relaxed, yet your body may feel off. A gentle week of nourishing meals is the perfect answer.",
    body: [
      "Coming home from holiday is bittersweet. You feel relaxed, yet your body may feel off. Rich food and travel often leave you heavy and tired.",
      "A gentle reset is the perfect answer. You do not need an extreme cleanse. Instead, a week of simple, nourishing meals does the work.",
      { h: "Why a reset works better than a detox" },
      "Harsh detoxes promise quick results. In truth, they often leave you drained. Skipping meals can stress the body further.",
      "A reset takes a kinder path. It feeds your body with whole, balanced food. As a result, your energy and digestion recover naturally.",
      "This approach is also easier to follow. Because you are not starving, you actually stick with it.",
      { h: "Days one and two: lighten the load" },
      "Start gently to ease your system back. Focus on vegetables, soups and plenty of water. These foods are light and easy to digest.",
      "Our chilled soups and fresh salads fit these days well. They settle the stomach without weighing you down. So you feel lighter almost at once.",
      { h: "Days three to five: rebuild steady energy" },
      "Now add steady fuel to the plan. Include good protein with each meal. Pair it with vegetables and whole grains.",
      "This balance keeps your energy level all day. It also supports your muscles and focus. Our balanced mains make this stage simple.",
      { h: "Days six and seven: support your gut" },
      "End the week by caring for your gut. Choose fibre-rich foods and fermented options. Both help your good bacteria recover.",
      "A happy gut lifts your whole body. You sleep better and feel brighter.",
      { h: "Let us plan your reset week" },
      "A full week of healthy meals sounds like effort. With Healthy Kitchen, it is effortless. We plan, cook and deliver each dish, so you can rebalance one fresh meal at a time.",
    ],
  },
  {
    slug: "mineral-rich-summer-eating",
    category: "Wellness",
    date: "20 Jul 2026",
    image: "https://healthykitchen.delivery/wp-content/uploads/2026/07/Hydration-Dubai-e1784477503939.png",
    title: "Mineral-Rich Summer Eating: Foods That Put Back What the Heat Takes Out",
    excerpt: "Sweat carries more than water. Here are the foods that replace the minerals the heat takes out.",
    body: [
      "Summer heat makes you sweat all day. That sweat carries more than water. It also takes away key minerals your body needs.",
      "Food is the best way to replace them. The right ingredients restore what the heat removes. At Healthy Kitchen, we build our summer menu around this idea.",
      { h: "The minerals you lose in the heat" },
      "Sweat is rich in minerals. You lose magnesium, potassium and sodium with every drop. These minerals keep your muscles and nerves working.",
      "When levels fall, you feel it. Cramps, tiredness and poor sleep often appear. Therefore, summer is the season to focus on minerals.",
      { h: "Magnesium for calm and sleep" },
      "Magnesium helps your body relax. It supports steady sleep and eases muscle tension. So a good supply makes summer nights easier.",
      "Leafy greens are packed with magnesium. Nuts, seeds and beans add more. We include these foods across our menu for a reason.",
      { h: "Potassium for fluid balance" },
      "Potassium works closely with sodium. Together, they manage your fluid balance. As a result, they keep you properly hydrated.",
      "Many everyday foods are rich in potassium. Bananas, avocados and sweet potatoes all help. We weave them into our summer dishes.",
      { h: "Smart sodium, not too much" },
      "Sodium has a bad reputation, yet you still need some. It helps your body hold on to water. The key is the right amount from good sources.",
      "We season our meals with care. A balanced pinch of quality salt does the job. This keeps your hydration steady without going overboard.",
      { h: "Meals that restore and refresh" },
      "Our summer dishes combine all these minerals. Each meal is fresh, light and balanced. So you refuel without feeling heavy.",
      "Eating well in the heat should be easy. Let Healthy Kitchen handle the balance for you.",
    ],
  },
  {
    slug: "5-signs-your-gut-needs-a-reset",
    category: "Gut Health",
    date: "12 Jul 2026",
    title: "5 Signs Your Gut Needs a Reset",
    excerpt: "Bloating, brain fog, and energy crashes are often your gut asking for help. Here's what to watch for — and where to start.",
    body: [
      "Your gut does far more than digest lunch. It shapes how you absorb nutrients, how steady your energy feels through the day, and — increasingly, research suggests — how clear your head is. When it's out of balance, the signals are usually there long before anything feels seriously wrong.",
      "The most common ones: bloating that shows up after ordinary meals, energy that dips hard mid-afternoon, skin that flares for no obvious reason, sugar cravings that feel bigger than hunger, and digestion that swings between sluggish and urgent. None of these are dramatic on their own — which is exactly why they're easy to ignore.",
      "The fix is rarely complicated. Start by simplifying what you eat for a week or two: whole foods, less processed sugar, and something fermented — yogurt, kimchi, sauerkraut — most days. Drink water before you reach for a snack. Give meals time to digest before the next one.",
      "If you want the reset done for you, that's exactly what our Gut Healing Protocol is built around — nutrient-dense, easy-to-digest meals designed to calm inflammation and rebuild a steadier baseline, one delivery at a time.",
    ],
  },
  {
    slug: "why-we-cook-without-sugar-dairy-gluten",
    category: "Nutrition",
    date: "05 Jul 2026",
    title: "Why We Cook Without Sugar, Dairy, or Gluten",
    excerpt: "It's not a trend — every dish we make starts from the same three rules. Here's the thinking behind them.",
    body: [
      "Every plan on our menu is built dairy-free, gluten-free, and sugar-free from the first ingredient. Not because it's fashionable, but because it's the version of clean eating that works for the widest range of people without asking anyone to compromise on taste.",
      "Sugar is the easiest one to justify: added sugar drives energy spikes and crashes, and it hides in more \"healthy\" products than most people realize. Cutting it at the source means we control exactly how satisfying a dish is — with fruit, spice, and technique instead.",
      "Dairy and gluten are quieter culprits. Plenty of people carry a mild sensitivity to one or both without ever being formally diagnosed — a bit of bloating, a bit of fatigue, written off as normal. Removing them by default means our food works for you whether or not you've ever tested for it.",
      "The part people are usually surprised by: none of this tastes like a restriction. Good spice work, quality fat, and fresh produce do more for flavor than sugar or dairy ever did — you just have to cook it that way from day one.",
    ],
  },
  {
    slug: "eating-out-in-dubai-a-nutritionists-guide",
    category: "Lifestyle",
    date: "28 Jun 2026",
    title: "A Nutritionist's Guide to Eating Out in Dubai",
    excerpt: "Dining out doesn't have to derail your plan. Simple swaps and questions that keep any menu on your side.",
    body: [
      "Dubai makes it easy to eat well and easy to eat badly — often at the same table. The difference usually comes down to a few small habits, not willpower.",
      "Start with a glass of water before the menu arrives; it slows down ordering and takes the edge off false hunger. Scan for a protein-and-vegetable anchor first, then build around it, rather than starting from the bread basket.",
      "Sauces and dressings are where most extra sugar and oil hide — ask for them on the side and you keep control without changing your order. The same goes for rice and bread: not off-limits, just worth choosing on purpose rather than by default.",
      "Most of all, treat eating out as the enjoyable part of the week it's meant to be. One meal doesn't undo a good plan — consistency the rest of the week is what actually moves the needle.",
    ],
  },
];
