/* Healthy Kitchen — intolerance test ingredient catalogue (283 items, from the live site) */
window.HK_INTOLERANCE_CATS = [
  { key: "milk-eggs", label: "Milk & Eggs", icon: "milk", items: ["Egg yolk","Egg white","Buttermilk","Cow's milk","Camembert","Gouda","Emmental","Cottage cheese","Mozzarella","Parmesan","Buffalo milk","Camel milk","Goat milk","Goat cheese","Quail egg","Sheep cheese","Sheep milk","Cow's milk Bos d 4 (Alpha-Lactalbumin)","Cow's milk Bos d 8 (Casein)","Cow's milk Bos d 5 (Beta-Lactoglobulin)"] },
  { key: "meat", label: "Meat", icon: "beef", items: ["Duck","Beef","Veal","Venison","Goat","Stag","Horse","Chicken","Turkey","Rabbit","Lamb","Ostrich","Pork","Boar"] },
  { key: "fish", label: "Fish & Seafood", icon: "fish", items: ["Caviar","Eel","Noble crayfish","Cockle","Crab","Atlantic herring","Carp","European anchovy","Northern pike","Atlantic cod","Abalone","Lobster","Shrimp mix","Squid","Monkfish","Haddock","Hake","Common mussel","Octopus","Trout","Oyster","Northern prawn","Scallop","Razor shell","European plaice","Thornback","Ray","Venus clam","Salmon","European pilchard","Turbot","Mackerel","Atlantic redfish","Sepia","Sole","Gilt-head bream","Tuna","Swordfish"] },
  { key: "cereals", label: "Cereals & Seeds", icon: "wheat", items: ["Gluten","Wheat","Rye","Polish wheat","Rapeseed","Wheat bran","Spelt","Einkorn","Emmer","Sunflower","Barley","Linseed","Malt (barley)","Amaranth","Oat","Hempseed","Quinoa","Chickpea","Pumpkin seed","Buckwheat","Lupine seed","Rice","Millet","Poppyseed","Pine nut","Sesame","Wheatgrass","Durum","Corn","Wheat gliadin"] },
  { key: "nuts", label: "Nuts", icon: "nut", items: ["Pecan nut","Hazelnut","Cashew","Brazil nut","Sweet chestnut","Coconut milk","Coconut","Kola nut","Tigernut","Macadamia","Pistachio","Almond","Walnut"] },
  { key: "legumes", label: "Legumes", icon: "bean", items: ["Peanut","Soy","Lentil","White bean","Green bean","Pea","Sugar pea","Tamarind","Mung bean"] },
  { key: "fruits", label: "Fruits", icon: "apple", items: ["Strawberry","Cherry","Papaya","Pineapple","Lime","Lemon","Watermelon","Kiwi","Grapefruit","Tangerine","Orange","Melon","Fig","Date","Physalis","Apricot","Plum","Peach","Nectarine","Pomegranate","Pear","Gooseberry","Red currant","Blackberry","Lychee","Apple","Mango","Mulberry","Banana","Passion fruit","Raspberry","Elderberry","Blueberry","Cranberry","Grape","Raisin"] },
  { key: "vegetables", label: "Vegetables", icon: "carrot", items: ["Shallot","Onion","Leek","Chives","Wild garlic","Celery bulb","Celery stalk","Horseradish","White asparagus","Bamboo sprouts","Chard","Red beet","Cabbage","Cauliflower","White cabbage","Brussels sprouts","Kohlrabi","Broccoli","Romanesco","Red cabbage","Green cabbage","Savoy","Turnip","Pok-choi","Chinese cabbage","Caper","Endive","Radicchio","Chicorée","Pumpkin Butternut","Pumpkin Hokkaido","Kiwano","Zucchini","Cucumber","Artichoke","Carrot","Arugula","Fennel (bulb)","Sweet potato","Watercress","Olive","Parsnip","Avocado","Radish","Garlic","Eggplant","Potato","Tomato","Spinach","Nettle leaves","Lamb's lettuce"] },
  { key: "spices", label: "Spices", icon: "flame", items: ["Dill","Tarragon","Nutmeg","Mint","Paprika","Cayenne pepper","Chili (red)","Caraway","Cinnamon","Curry","Coriander","Cumin","Turmeric","Lemongrass","Cardamom","Juniper berry","Bay leaf","Basil","Marjoram","Mustard","Oregano","Parsley","Anise","Pepper (black/white/green/red/yellow)","Rosemary","Sage","Clove","Thyme","Fenugreek","Vanilla","Ginger"] },
  { key: "mushrooms", label: "Mushrooms", icon: "cloud-drizzle", items: ["White mushroom","Boletus","Chanterelle","Enoki","French horn mushroom","Oyster mushroom"] },
  { key: "novel", label: "Novel Food", icon: "sparkles", items: ["House cricket","Baobab","Aloe","Greater burdock root","Aronia","Safflower oil","Chlorella","Ginkgo","Maca root","Migratory locust","Tapioca","Ginseng","Guarana","Almond milk","Nori","Chia seed","Yacón root","Spirulina","Dandelion root","Mealworm","Wakame"] },
  { key: "coffee-tea", label: "Coffee & Tea", icon: "coffee", items: ["Tea, black","Tea, green","Coffee","Chamomile","Peppermint","Moringa","Hibiscus","Jasmine","Cocoa"] },
  { key: "others", label: "Others", icon: "layers", items: ["Cane sugar","Agar agar","Honey","Aspergillus niger","Hops","Baker's yeast","Brewer's yeast","Elderflower","M-Transglutaminase (meat glue)"] },
  { key: "ccd", label: "CCD", icon: "test-tube", items: ["Human Lactoferrin"] },
];
